---
title: "Module 8:  Regression"
author: "Robert A. Stevens, robertandrewstevens@gmail.com"
date: "December 8, 2014"
output: pdf_document
---

**Typical Six Sigma Phase:**  Analyze

**Six Sigma Green Belt Body of Knowledge Subtopic:**  Simple linear correlation and regression

**Six Sigma Green Belt Body of Knowledge Description:**

- Interpret the correlation coefficient and determine its statistical significance (p-value); recognize the difference between correlation and causation.

- Interpret the linear regression equation and determine its statistical significance (p-value).

- Use regression models for estimation and prediction.

# Homework

Read **Textbook** sections listed below.

Review **Web Links** listed below.

Complete **Exercises** below.

## Textbook:

23  Correlation and Simple Linear Regression [Introduction only]  
23.1	S4/IEE Applications Examples:  Regression  
23.3	Correlation  
23.4	Example 23.1:  Correlation  
23.5	Simple Linear Regression  
23.6	Analysis of Residuals  
23.7	Analysis of Residuals:  Normality Assessment  
23.8	Analysis of Residuals:  Time Sequence  
23.9	Analysis of Residuals:  Fitted Values  
23.10	Example 23.2:  Simple Linear Regression  
26	Multiple Regression, Logistic Regression, and Indicator Variables [Introduction only]  
26.1	S4/IEE Application Examples:  Multiple Regression  
26.2	Description  
26.3	Example 26.1:  Multiple Regression

## Web Links:

Regression Modeling and Analysis

http://home.ubalt.edu/ntsbarsh/Business-stat/opre504.htm#rregmodel

Basic Statistics

http://www.statsoft.com/textbook/stathome.html

Linear Regression (Multiple Regression)

http://www.statsoft.com/textbook/stathome.html

NIST/SEMATECH e-Handbook of Statistical Methods Chapter 4:  Model

http://www.itl.nist.gov/div898/handbook/ 

## Exercises:

The data provided in “Module08 Regression.xls” tab “Abscombe” consists of four sets of paired data:  (x1, y1), (x2, y2), (x3, y3), and (x4, y4).  Estimate the regression equation for each of the four pairs.  Then perform residual analysis for each of the four pairs.  Based on the residual analysis, which, if any, are valid regression equations?

Review the “Correlation and Regression Analysis:  A Quick Tutorial” handout and rework the two examples using the data in tabs “Model” and “Load Cell” in “Module08 Regression.xls” to reproduce the plots and analysis shown as you do so.

The data provided in “Module08 Regression.xls” tab “Functional Tester” consists of three sets of paired data:  (Tester.Dn, Display.Dn), (Tester.Up, Display.Up), and (Tester.Ctr, Display.Ctr).  Estimate the regression equation and perform residual analysis for each of the three pairs.  For each pair of data, can you reasonability predict the Display value from the Tester value?
