---
title: "Module 9:  Measurement Systems Analysis (MSA)"
author: "Robert A. Stevens, robertandrewstevens@gmail.com"
date: "December 8, 2014"
output: pdf_document
---

**Typical Six Sigma Phase:**  Measure

**Six Sigma Green Belt Body of Knowledge Subtopic:**  Measurement system analysis

**Six Sigma Green Belt Body of Knowledge Description:**  Calculate, analyze, and interpret measurement system capability using repeatability and reproducibility (GR&R), measurement correlation, bias, linearity, percent agreement, and precision/tolerance (P/T).

# Homework

Read **Textbook** sections listed below.

Review **Web Links** listed below.

Review **Measurement Systems Analysis Notes** after the **Exercises** below.

Complete **Exercises** below.

## Textbook:

3.13  Example 3.3:  Experimentation Trap – Measurement Error and Other Sources of Variability  
12	Measurement Systems Analysis [Introduction only]  
12.1	MSA Philosophy  
12.2	Variability Sources in a 30,000-foot Level Metric  
12.3	S4/IEE Application Examples:  MSA  
12.4	Terminology  
12.5	Gage R&R Considerations  
12.6	Gage R&R Relationships  
12.7	Additional Ways to Express Gage R&R Relationships  
12.8	Preparation for a Measurement System Study  
12.9	Example 12.1:  Gage R&R  
12.10	Linearity  
12.11	Example 12.2:  Linearity  
12.16	A 5-Step Measurement Improvement Process  
12.17	Example 12.5:  A 5-Step Measurement Improvement Process  

## Web Links:

Process Analysis:  Gage Repeatability and Reproducibility

http://www.statsoft.com/textbook/stathome.html

NIST/SEMATECH e-Handbook of Statistical Methods Chapter 2:  Measure

http://www.itl.nist.gov/div898/handbook/

## Exercises:

**Gage R&R:**  “Module02 Basic Statistics.xls” tab “TAB4-1” contains the weights of 10 silicon wafers measured by 3 operators.  Is the measurement system adequate in terms of R&R?  [This data was already processed and analyzed in Module 2 – if you saved it.]

**Gage Linearity:**  “Module06 MSA.xls” tab “Linearity Exercise 1” contains the results of a gage linearity study.  Analyze the gage’s linearity and bias using Statistica’s Gage Linearity tool with Process Variation = 0.25.  What can you conclude?

**Gage Linearity:**  An industrial thermometer manufacturer uses 2 thermometers with an NIST traceable thermometer to measure an oven’s temperature from -40 C to 200 C.  “Module06 MSA.xls” tab “Linearity Exercise 2” contains the results of their gage linearity study.  Complete a linearity analysis for each using Process Variation = 10.  Which is better?

## Measurement Systems Analysis Notes

### Topics

- Overview

- Bias

- Linearity

- Stability

- Gage R&R

- Variable Gage R&R:  SPC Method; ANOVA Method

- Attribute Gage R&R

- Excessive Within-Part Variation

- Multiple Readings

- Destructive Testing Gage R&R

### Objectives

- Understand the language of Measurement Systems Analysis (MSA)

- Recognize the importance of measurement

- Know how to perform MSA and how to interpret results

- Use and understand Statistica to evaluate MSA data
    + Statistics > Industrial Statistics & Six Sigma > Process Analysis >
        - Gage repeatability & reproducibility
        - Gage linearity

### References

- Automotive Industry Action Group (AIAG)
    + *Advanced Product Quality Planning (APQP) and Control Plan*
    + *Statistical Process Control (SPC)*
    + *Measurement Systems Analysis (MSA)*
    + *Production Part Approval Process (PPAP)*

- *Evaluating the Measurement Process* by Donald J. Wheeler and Richard W. Lyday

### Overview

#### Measurement Systems Analysis

- Determine if the measurement system is adequate to measure part-to-part variability in the process,  a.k.a. Gauge Repeatability & Reproducibility

- PPAP Section 4.11.4:  “Evidence is required that appropriate statistical studies have been conducted to analyze the variation…”

#### The Science of Measurement

- “I often say that when you measure what you are speaking about and express it in numbers, you know something about it” - Lord Kelvin

- He clearly stressed that little progress is possible in any field of investigation without the ability to measure

- The progress of measurement is, in fact, the progress of science

- The foundation of a experiment is measurement

- “Any technique can be useful if its limitations are understood and observed” - W. Edwards Deming

#### Ideal Measurement Systems

- Measurements are traceable to the National Institute of Standards and Technology (NIST)

- Resolution is no greater than one-tenth of the smaller of either the process variability or the specification limits

- Variation must be “small” compared with process variability or specifications

- Statistical stability:  Variation is due to common causes, not special causes

#### Knowledge to Be Obtained

- How big is the measurement error?

- What are the sources of measurement error?
    + Operators (Experience, training, eyesight, etc.)
    + Gauge (Worn, warm-up, etc.)
    + Noise (Temperature, pressure, humidity)
    + Within part variation (Out of round, flatness, etc.)

- Is the gage stable over time?

- Is the gage capable for this study?

- Is the gauge good enough for production environment?

- How do we improve the measurement system?

- Caution:  The results of MSA should not be used to predict future performance of the measurement system

#### MSA Applications

- Mostly common used when
    + Introduce a new measurement process or measuring equipment
    + Changes are made to the current measurement system

- Used to compare 
    + One measuring device against another
    + Measuring device before and after repair

- Used to determine 
    + True process variation
    + Fitness of gage

- Used for problem solving
    + Evaluate gage suspected of being bad
    + Only “common cause” variation is detected on control chart

#### Measurement

- The assignment of numbers to material things to represent the relationships among them with respect to particular propertie - C. Eisenhart (1963)

- Think of measurement as a process - All processes have variation

#### Measurement Systems

- Represent a sub-processes within processes - They are subject to variation

- What could be the source of variation?

- Why do measurements vary?

#### Sources of Measurement Variation

- Environment

- Material

- Operator

- Methods

- Gages

#### Measurement System Errors

- *Accuracy* describes the difference between the measurement and the part’s actual value

- *Precision* describes the variation you see when you measure the same part repeatedly with the same device

#### Sources of Variation

- Total Variability = Product Variability + Measurement Variability

- Observed Variability = Actual Variability + Measurement Error

#### The Nature of Process Variation

- Location Errors

- Spread Errors

#### Measurement Error Math Model

- Location:  Measurement System Bias determined through “Accuracy study”

- Spread:  Measurement System Variability determined through “R&R Study”

#### Terminology

- Location related terms:  Accuracy
    + Bias
    + Linearity
    + Stability (drift)

- Spread related terms:  Precision
    + Repeatability
    + Reproducibility

### Bias

#### Bias Definition

- The difference between the observed average of measurements and the reference value
    + Compare gage readings against a reference standard

- Bias is often referred to as “accuracy,” but that can cause confusion

#### Reference Value

- Value that serves as an agreed-upon reference for the measured values

- Can be determined by averaging several measurements with a higher level of measuring equipment e.g., metrology lab or layout equipment

#### Determining Gage Bias

- To determine the measurement system’s bias at a specific location in the process range, it is necessary to obtain an accepted reference value of a part
    + Usually done with tool room or layout inspection equipment
    + Derived from these readings to be compared later with the appraiser’s observed averages from a Gage R&R study

- If it is not possible to measure all the sample parts in this manner, then
    + Measure one of the sample parts precisely on tool room or layout inspection equipment
    + Have one appraiser measure the same parts a minimum of 10 times, using the gage being evaluated
    + Calculate the average of the readings
    + The difference between the reference value and the observed average represents the measurement system’s bias

#### Example

- Choose a set of parts for the measurement and measure them with a caliper (resolution 0.01) and calculate the average

- Take the same parts and measure them with a micrometer (resolution 0.001) and calculate the average

- Compare the two averages - The difference is the bias of the caliper

#### Bias Acceptance Criteria

- There is no acceptance criteria in the AIAG MSA manual, so consider statistical test or confidence interval

- Usually measurement bias problems are relatively easy to fix, compared to other measurement errors

#### Causes of Bias

- If the bias is relatively large, look for these possible causes:
    + Error in the master
    + Worn components
    + Instrument 
        - made to the wrong dimension
        - measuring the wrong characteristic
        - improperly calibrated
        - used improperly by operator
        - damaged
        - read incorrectly
    + Part set incorrectly (wrong datum)

### Linearity

#### Measurement Error

- Measured Value (y) = True Value (x) + Measurement Error (e)

- Is the Measurement Error (e) consistent (i.e. linear)?

#### Linearity

- Difference between the bias values through the expected operating range of the gage

- Determined by a regression line between the reference values and bias

#### Linearity Acceptance Criteria

- There is no acceptance criteria in the AIAG MSA manual

- The linear relationship is measured by the R^2^

- Linearity is determined by the slope of the line of the best fit

#### Causes of Poor Linearity

- If the linearity is relatively large, look for:
    + Error in the minimum or maximum master
    + Worn instrument
    + Internal instrument design characteristics
    + Instrument not calibrated properly at both lower and upper end of the operating range

#### Calculations

- Model:  y = ax + b

- Bias = ax + b

- Linearity = |slope|*process variation

- %Linearity = 100[linearity/process variation] = 100|slope|

- Goodness of Fit (R^2^) = 1 - SS(Error)/SS(Total)

#### Linearity and Bias Example

- A plant foreman chose 5 parts that represented the expected range of the measurements

- Each part was measured by layout inspection to determine its reference value

- Then 1 operator randomly measured each part 12 times

- A Gage R&R Study using ANOVA was performed to get the process variation = 14.1941

- See “gagelin.xls”

- For this gage,
    + Linearity is 13% of the overall process variation
    + Bias is less than 1% of the overall process variation

### Stability

#### Stability Definition

- The total variation in the measurements obtained with a measurement system on the same master or parts when measuring a single characteristic over an extended time period

- The distribution of measurements should remain constant and predictable over time for both mean and standard deviation

#### Stability Evaluation

- Unlike the other four MSA errors (bias, linearity, reproducibility & repeatability), there is no need to calculate measurement system stability indices

- Evaluate using a control chart of master part(s) measurements taken on a periodic basis
    + An out-of-control point is the signal that calibration is required
    + Calibration without an out-of-control signal will likely increase the variation (i.e., tampering)

### A Tale of Two Operators:  Accuracy, Calibration, Good Intentions and the Road to Hell

#### A Tale of Two Operators:  Operator A

- Operator A was always very careful to ensure that his test instrument was calibrated

- Every hour he regularly measured and recorded the reading for a part which was known as a “reference standard”

- If this reading was not equal to the “accepted value” for the reference standard, he would adjust his instrument to compensate for the difference between his measured value and the accepted value

- Because of this hourly re-calibration of his instrument, Operator A was thought to be a committed, improvement-oriented employee

#### A Tale of Two Operators:  Operator B

- Operator B, on second shift, used the same instrument as Operator A

- Although Operator B also took hourly readings of the standard, he did not make adjustments in the same manner as Operator A

- Operator B did not adjust the instrument each hour based on a single reading 

- Instead, he would plot the value obtained for the reference standard on a control chart for individuals -- the Individual-X Chart
    + NOTE: The center-line for this control chart was fixed at the accepted value for the reference standard

- Only if this Individual-X Chart demonstrated a lack of control, would Operator B make an adjustment to his instrument

- Otherwise, he would proceed using the instrument without any adjustments

#### A Tale of Two Operators:  Comparision

- Operators A and B continued with their different calibration approaches for several months

- However, when constructing a map of the measurement process one day, a Black Belt discovered the existence of these discrepant calibration methodologies

- He decided to investigate the results obtained by the two approaches

- Since both operators had recorded the test values for the reference standard, he simply created two histograms of these values, as shown on the right
    + Repeated measurements of a single reference part
    + The scale shows the deviations from the “accepted value” for the reference standard

- Based on this study, the supervisor initiated a new calibration methodology

- Individual-X and Moving Range Charts were made a routine part of every calibration strategy

- Standard operating procedures were changed so that measuring system adjustments were to be made only in response to evidence of a lack of control

- As a result, a several measurement systems, which had been deemed inadequate by previous Gage R&R studies, showed a sudden and dramatic improvement due to the removal of over-calibration

### Gage R&R

#### Total Variation in the Measurement System

- Measure of natural variation of repeated measurements

- Terms:
    + Repeatability SigmaG
    + Reproducibility SigmaO

#### Repeatability SigmaG

- The variation in measurements obtained with one measurement instrument when used several times by *an appraiser* while measuring the identical characteristic on the *same part*
    + The inherent variability of the measurement system

#### Reproducibility SigmaO

- The variation in the average of the measurements made by *different appraisers* using the *same measuring instrument* when measuring the identical characteristic on the same part
    + Operator variability of the measurement system

#### Gage R&R Objective

- Access measurement system variability due to variation of both the measuring device and the operator in non-destructive testing on rigid parts:
    + Variation contributed by the measuring device
    + Variation contributed by individuals using the measuring system
    + Within part variation

#### A Typical Gage R&R Study

- Generally two or three operators

- Generally 10 units to measure

- Each unit is measured 2-3 times by each operator

#### Measurement Study Preparation

- Verify the correct variable is being measured

- Determine whether environmental factors (stability) have a significant influence on measurement system or not

- Determine if reproducibility is an issue
    + If it is, select the number of operators to participate
    + Operators selected should normally use the measurement system

- Determine within-part-variation is an issue

- Select samples that *represent the entire operating range*

- Insure defined gauging procedures are followed

- Measurements should be made in random order

- Study should be monitored by someone who recognizes the importance of conducting a reliable study

#### Gage R&R Study Procedure

- Calibrate the gage, or assure that it has been calibrated

- Have the first operator measure all the samples once in random order

- Have the second operator measure all the samples once in random order

- Continue until all operators have measured the samples once (this is Trial 1)

- Repeat above steps for the required number of trials

- Use Statistica or Attribute GR&R form to determine the statistics of the study
    + Repeatability and Reproducibility
    + %R&R
    + %Tolerance analysis

- Analyze results and determine action, if any

#### Main Question to Ask

- Before you make the final suggestion of the MSA study, ask “*Do the parts used in the MSA study properly reflect the product variation?*”
    + If yes, the information will be accurate
    + If no, the study will be flawed

#### Other Issues

- Number of operators
    + If process uses multiple operators, choose 2-4 at random
    + If process uses only one operator, or no operators, perform study without operator effects
        - Reproducibility effects ignored

- Number of samples
    + Select enough samples so that (# samples) * (# operators) > 15
    + If not practical or possible, choose number of trials so that:
        - if S x O < 4, trials = 6
        - if S x O < 5, trials = 5
        - if S x O < 8, trials = 4
        - if S x O < 15, trials = 3

#### Types of Gage R&R Studies

- Variable Gage R&R:  Units of measure, e.g. Newton, ft, in

- Attribute Gage R&R:
    + Pass / Fail
    + Break / OK
    + Subjective (cosmetic defects)
    + Feel, visual

- Destructive Gage R&R:  Part can only be measured once

### Variable Gage R&R

#### Statistics of Measurement Systems

- The Variance of the Measurement System is defined as:

- The Standard Deviation of the Measurement System is defined as:

### Gage R&R Calculations

- EV = Equipment Variation = Repeatability = 5.15*SigmaG

- AV = Appraiser Variation = Reproducibility = 5.15*SigmaO

- 5.15 was developed empirically to approximate 99% of the normal distribution variation

- R&R = Repeatability & Reproducibility = sqrt(EV^2^ + AV^2^)

- TV = Total Variation of PV and R&R = Sigmat = sqrt(R&R^2^ + PV^2^) = 5.15[Process Variation/6], if known

- PV = Part-to-Part Variation = 5.15*Sigmap = sqrt(TV^2^ - R&R^2^), if known

- %EV = 100*[EV/TV]

- %AV = 100*[AV/TV]

- %R&R = 100*[R&R/TV]

- %PV = 100*[PV/TV]

#### %R&R Acceptability Criteria

- %R&R < 10%:  Acceptable measurement system

- 10% <= %R&R <= 30%:  May be acceptable based upon importance of application, cost of measurement device, cost of repair, etc.

- %R&R > 30%:  Considered not acceptable - Every effort should be made to improve the measurement system

#### Control Charts

- R Chart
    + Repeatability
    + Discrimination

- X-bar Chart
    + Repeatability
    + Reproducibility
    + Part-to-part
    + At least 50% of the points outside of the control limits

#### Bar Chart

- Used to quantify the variation due to part and to contrast that value visually with the variation due to overall measuring system, operator, and measuring device

- Graphs the numbers found in the last table in the session window output
    + Each cluster will have a minimum of two bars like the one shown on the left

- When you add tolerance and/or process variation, you will get an additional set of bars for each value added

#### Interaction Plot

- Oper*Part Interaction
    + Average part measurements from each operator
    + Measurements different but not consistently higher or lower
    + If one operator measures consistently higher than other, the line will parallel, but separated

#### By Operator Plot

- Equivalent to a main effects plot

- Determine whether one operator consistently measures higher than another
    + Or whether the overall variability between operators’ individual measurements across parts is different

- If one operator measures consistently higher, the average will be shifted up and the red line will not be straight horizontal

- You can also assess whether the overall variability in part measurement is same using this graph

#### By Part Plot

- This is a main effects plot for part

- Shows the variability in measurements for each part across all operators

- When there is good discrimination, there will be very little variation around each part measurement, as compared to measurement differences between parts

#### Gage R&R Plot Guidelines

- Always look at the bar chart first
    + If the variation due to the measurement system is low, there is no need to look at the other graphs
    + When the variation attributable to the measuring system is higher than desired, the control charts, main effects and interaction plots can be used as diagnostic graphs

- Low variation due to the measuring system is shown in the following patterns:
    + Small average range on the R-bar chart
    + Narrow control limits on the X-bar chart
    + Overlaid lines on the Oper*Part graph
    + A straight horizontal line on the By Oper graph
    + Very similar individual measurement for each part across all operators on the By Part graph

#### Measurement System Discrimination

- Smallest measurement should be at most one-tenth of the total process capability (6Sigma) or tolerance
    + i.e. Min(X) < Tolerance/10

- Part-to-Part variation must be greater than the smallest unit of measure

- Range control chart provides best indication of inadequate discrimination
    + Occurs when only 1, 2 or 3 possible values for the range within the control limits exists 
    + Also if 4 values within control limits and > 1/4 are zero

#### Number of Distinct Categories (NDC)

- Part standard deviation divided by the total gage R&R standard deviation times 1.41 = 1.41(PV/R&R) 

- Also known as Effective Resolution

- The number of non-overlapping 97% confidence intervals that will span the range of product variation

- If NDC = 1
    + Unacceptable for estimating process parameters and indices
    + Only indicates whether the process is producing conforming or nonconforming parts
    + Can be used for control only if
        - The process variation is small when compared to the specifications
        - The loss function is flat over the expected process variation
        - The main source(s) of process variation causes a mean shift

- If  2 <= NDC <= 4
    + Generally unacceptable for estimating process parameters and indices
    + Only provides coarse estimates
    + Can produce insensitive variables control charts
        - Can be used with semi-variable control techniques based on the process distribution

#### Variable Gage R&R:  SPC Method

#### SPC Based Gage R&R

- Repeatability:  Based on the average range of all measurements for each part = SigmaG = R-bar/d2

- Reproducibility:    Based on the range of the average of all measurements for each operator = SigmaO = R-bar/d2

- d2 is determined by number of trials and number of parts times the number of appraisers

#### Variable Gage R&R Example - SPC Method

- 10 parts were selected that represent the expected range of the process variation

- 3 operators measured the 10 parts in random order - 2 times per part

- See “gageaiag.xls”

- Statistica Analysis:  Statistics > Industrial Statistics & Six Sigma > Process Analysis > Gage repeatability & reproducibility > Range Method > Options:  Process Tolerance = 0.4

- The measurement system variation from X-bar/R = 0.0021

- Measurement system variation contributes little to the overall observed variation
    + Part-To-Part contributes 93.7%

- NDC = 5 implies an adequate measuring system

### Variable Gage R&R:  ANOVA Method

#### ANOVA Based Gage R&R

- Balanced 2-factor factorial design with random factors
    + “Parts”, “Operators” and “Operator*Part”

- The ANOVA method is more accurate than the SPC Method
    + ANOVA considers the Operator*Part interaction

#### Traditional Approach

- The SPC method provides estimates of the variance components of Repeatability, Reproducibility and Total Measurement System Error using the following model:

#### Math Model for a Measurement

- Consider the three factors:  Part (P), Operator (O), Trial (T)

- We can use ANOVA to estimate the variance components for the following model:
    + y = Mean + P + O + P*O + Error

- The ANOVA model in terms of GR&R:

- Only the variance component of Part is not considered measurement error

- All the other components are considered part of the measurement error

#### ANOVA vs. SPC Gage R&R

- ANOVA model:

- SPC model:

#### Variable Gage R&R Example - ANOVA Method

- Same data as SPC Method Example

- Statistica Analysis:  Statistics > Industrial Statistics & Six Sigma > Process Analysis > Gage repeatability & reproducibility > ANOVA > Options:  Process Tolerance = 0.4

- The measurement system variation from X-bar/R (0.0021) is much smaller than what was found with ANOVA (0.0044)
    + Significant Operator by Part interaction

- Measurement system variation contributes little to the overall observed variation
    + Part-To-Part contributes 89.33%

- NDC = 4 implies a marginally adequate measuring system

### Attribute Gage R&R

#### Why Attribute Gage Studies?

- To determine
    + How well quality inspectors are conforming to known boundary samples
    + How well quality inspectors are conforming to themselves
    + If the existing boundary samples provide sufficient criteria for quality inspectors
    + If a particular operator requires additional training
    + If there is a tendency to reject good parts or accept bad parts

#### Attribute Measurement Processes

- Attribute inspection:
    + Classifies a unit as either Conforming or Nonconforming
    + Counts the number of “non-conformities” per inspection unit

- A “perfect” attribute measurement process would:
    + Correctly classify every unit as Conforming or Nonconforming
    + Always produce a correct count of a unit’s non-conformities

#### Attribute Measurement Processes

- Some attribute inspections require little judgment - The correct answer is obvious
    + Example:  Destructive test results - “It broke” or “It did not break”
    + Example: “It fits” or “It does not fit”

- More often, it is extremely subjective:
    + Especially in nondestructive testing/evaluation
    + Training and Operational Definitions are crucial

#### Influencing Factors

- Individual abilities
    + Visual acuity
    + General intelligence an comprehension
    + Method of inspection

- Organizational and social
    + Training
    + Peer standards
    + Management standards
    + Knowledge of people producing the item
    + Proximity of inspectors
    + Re-inspection vs. immediate shipping

- Task
    + Defect probability
    + Fault type
    + Number of faults occurring simultaneously
    + Time allowed for inspection
    + Frequency of rest periods
    + Illumination
    + Time of day
    + Objectivity of conformance standards
    + Inspection station layout

#### Attribute Gage R&R Method

- Select 20 to 30 parts from the process that include both good and bad samples

- Two or three appraisers independently measure each part twice (in random order)

- Use the “MSC_attr.xls” spreadsheet to record the data and calculate the score

- An acceptable “Effectiveness” score is 100%

- Interpret the results and take appropriate action

#### “MSC_Attr.xls”

- Screen % Effective Score is a % error against known population of deemed good by local experts
    + 100% is the target for screen effectiveness

- If % appraiser score is less than 100%,  training is required
    + Focus area of weakness

- Attribute legend can be what defect codes are needing a score
    + Pass/Fail, 1/0, Good/Bad, etc.

### Excessive Within-Part Variation

#### Quantifying Excessive Within-Part Variation

- Within-part variation affects the estimate of repeatability, reproducibility, or both

- Need to separate from gage repeatability variation for a better gage assessment
    + Out of round, total run out, flatness, etc.

- Procedure is identical to X-bar/R method plus
    + Scan completely to span full range of variation for each parts (e.g., parts are rotated 360 degree) 
    + Record highest and lowest readings for each part

- Each part goes through this process at least twice by each appraiser and results are recorded

### Multiple Readings

#### Reducing Variation with Multiple Readings

- If variation of the present measurement system is not acceptable
    + Redesign gage or
    + Buy a new gage

- If the cost is an issue, you can reduce the Gage R&R by taking multiple statistically independent measurement readings

- See page 94 in the AIAG MSA Manual

- The acceptable performance criteria depends on the characteristic, process, and costs
    + Since we are using statistics to predict performance, the answers are not always black and white

#### Procedure

- Determine the number of multiple readings required to meet an acceptable level of variation

- Follow the gage study procedure

- This works because
    + The distribution of individual and average measurements has the same numeric value
    + The variance of the distribution of averages is equal to the variance of the distribution of individuals divided by the sample size

#### Example

- 31% of tolerance R&R variation - 5.15 spread equal to 0.25

- Want to reduce this figure to at least 20%

- Determine the number of multiple readings required to meet the desired 20% criteria

- Steps
    + 31%/0.25 = 20%/X
    + X = 0.129, which would have an equivalent 5.15 spread
    + (5.15)(SigmaXbar^2) = (5.15)(Sigma)^2/n
    + 0.129 = 0.25/sqrt(n)
    + n = 3.76 = 4 (rounded to nearest integer)

### Destructive Testing Gage R&R

#### Destructive Testing GR&R

- When performing a Destructive Testing Gage R&R, one must make every effort to obtain and maintain consistency from one “reference standard sample” to the next

- With sources which deteriorate with age, one will need to chart several reference standards simultaneously

- If it is impossible or impractical to repeatedly measure reference standards, one may use duplicate measurements of production samples to check the consistency of the measurement process

- The range of such duplicate measurements (or triplicate or quadruplicate measurements) can be plotted on an ordinary Range chart

- An out-of-control range will indicate an inconsistent measurement

- Use Gage R&R Nested Study when each part can only measured by only one operator, e.g. destructive tests

- Assumption is that all parts within a single batch are identical 
    + If assumption is not met, then part-to-part variation within a batch will mask the measurement system variation
    + If assumption met
        - All operators measure parts from each batch - use Gage R&R Crossed
        - Each batch is only measured by a single operator - use Gage R&R Nested

#### Example

- Measure viscosity on 2 samples from 7 lots

- Assume samples represent duplicate measurements

- Therefore, sample differences represent measurement error
