---
title: "Module 11:  Sample Size"
author: "Robert A. Stevens, robertandrewstevens@gmail.com"
date: "December 8, 2014"
output: pdf_document
---

**Typical Six Sigma Phase:**  Analyze

**Six Sigma Green Belt Body of Knowledge Subtopic:**  Basics

**Six Sigma Green Belt Body of Knowledge Description:**

- Define and distinguish between statistical and practical significance and apply tests for significance level, power, type I and type II errors.

- Determine appropriate sample size for various tests.

# Homework

Read **Textbook** sections listed below.

Review **Web Links** listed below.

Complete **Exercises** below.

## Textbook:

17.2  Sample Size:  Hypothesis Test of a Mean Criterion for Continuous Response Data  
17.3	Example 17.1:  Sample Size Determination for a Mean Criterion Test  
17.6	Example 17.3:  Sample Size – An Alternative Approach  
18.2	Sample Size:  Hypothesis Test of an Attribute Criterion  
18.3	Example 18.1:  Sample Size – a Hypothesis Test of an Attribute Criterion  
18.4	Confidence Intervals for Attribute Evaluations and Alternative Sample Size Considerations  
18.5	Reduced Sample Size Testing for Attribute Situations  
18.6	Example 18.2:  Reduced Sample Size Testing – Attribute Response Situations  
19.3	Sample Size:  Comparing Means  
20.3	Sample Size:  Comparing Proportions  
29.3	Sample Six Considerations for a Continuous Response Output DOE  
D.1	DOE:  Sample Size for Mean Factor Effects

## Web Links:

Sample Size Determination

http://home.ubalt.edu/ntsbarsh/Business-stat/opre504.htm#rssss

Process Analysis:  Sampling Plans

http://www.statsoft.com/textbook/stathome.html

Power Analysis

http://www.statsoft.com/textbook/stathome.html

Java applets for power and sample size

http://stat.uiowa.edu/~rlenth/Power/

## Exercises:

1.  A vendor stated that the mean life of a part you are considering is 10 years, and you want to test whether this is true (using an accelerated test, of course, and assuming the part failure times follow a Normal distribution).  You decide to test:

    H0: Mean = 10 years versus H1: Mean != 10 years

Based on similar parts, you believe that the standard deviation = 2.5 years.  You would like to have Alpha = 0.10 and are willing to accept Mean1 = 10 +/- 1.0 years with Beta = 0.10.  What should “n” be?


2.  After completing Problem 1, you realize that you don’t really care if the part has a mean life greater than 10 years, but you do care if the mean life is less than 10 years.  So, you now decide to test:

    H0: Mean >= 10 years versus H1: Mean < 10 years

Just like before, you believe the standard deviation = 2.5 years, you would like to have Alpha = 0.10, and you are willing to accept Mean1 = 9.0 years with Beta = 0.10.  Now what should “n” be?
